runtime: nodejs10

instance_class: F2

service: scrapper

env_variables:
    MONGO_DB_URI: 'mongodb+srv://headeralishah:NpanOw6eSoCnsi8Z@cluster0.lrmmd.gcp.mongodb.net/mypricee-dev?retryWrites=true&w=majority'

